### ISSUE TITLE
luny -> loony?

### ISSUE THREAD

**Issue by tuskpot** [standardebooks/ella-cheever-thayer_wired-love#10]
Here's one last note. The book uses "luny", but I would expect "loony" as the modern spelling. [Google N-gram](https://books.google.com/ngrams/graph?content=luny%2Cloony&year_start=1800&year_end=2019&corpus=26&smoothing=3&direct_url=t1%3B%2Cluny%3B%2Cc0%3B.t1%3B%2Cloony%3B%2Cc0) seems to support this.

> “[…]She seems all right enough with the exception of these vagaries. But she is a perfect conundrum to me.”
> “A bit luny, I think,” said the gentleman, who had asked the question.</p>

Would you agree with that change?

There are a few other SE books that also use "luny", although I haven't looked at them closely. Is this a candidate for modernize-spelling, too?

I'm willing to review and work up some pull requests if you would like, but I didn't want to start anything without checking.

**Comment by acabal** [comment]
Yes, good catch. I'll do this myself and add it to the script.
