### ISSUE TITLE
Remove quotation marks on all call signs?

### ISSUE THREAD

**Issue by tuskpot** [standardebooks/ella-cheever-thayer_wired-love#3]
Throughout the book, telegraph operators are referred to by their call signs, which are a single letter. These call signs appeared in quotation marks in the original scans. There are three characters who are referred to this way:

- "C" is the story's love interest.
- "N" is the narrator, Nattie.
- "Em" is an otherwise unnamed operator along their line.

In the SE edition, quotation marks were removed from all uses of "C", because it appears a lot, and the frequent quotation marks would be distracting. The other two call signs are used less frequently, and their quotes were not removed. The result is inconsistent, with some call signs having quotes and others not, even within the same sentences. Here are a few examples.

> Of course the sudden cessation of the intimacy between C and “N” was a theme of much surprise and bantering comments along the line, especially from “Em.”

> And all this time it never occurred to them that excepting “N” was for Nattie, and C for Clem, they knew really nothing about each other, not even their names.

> “Oh! it is you, is it, ‘N’?” responded C, “I thought so, but wasn’t quite sure. Yes, you, may ‘break’ at every word, and I will still be amiable.”

> Having bade “Em” goodbye, and closed the key, he said to Nattie, verbally[…]

In general, I would prefer to remove the quotation marks from all except the first usage of each call sign. In the second example only, maybe it would be better to restore the quotation marks on both letters instead of removing them ("N" was for Nattie, and "C" for Clem), but as long as they're consistent, I don't have a strong opinion either way.

Let me know what you think. If this is a desired change, I can put together a pull request.

**Comment by acabal** [comment]
I agree, can you do that please? Thanks!

**Comment by tuskpot** [comment]
While preparing these changes, I realized that both "Em." and "Em" are used in different places. "Em." with a period is used in chapter 3, and "Em" without a period is used in chapter 11. There is one other appearance, but it ends the sentence, so the period is ambiguous.

I would like to standardize the punctuation as part of this change, and my preference is to drop the period from all uses. This seems consistent with the usage of C and N.

Does that sound okay?

**Comment by acabal** [comment]
Is Em short for something?

**Comment by tuskpot** [comment]
The book never says one way or the other. For the other call signs, "C" is short for Clem and "N" is short for Nattie, so I would guess that "Em" is also short for a name.

**Comment by acabal** [comment]
OK, that's fine then.
