### ISSUE TITLE
Semicolons closing dialog instead of commas?

### ISSUE THREAD

**Issue by tuskpot** [standardebooks/ella-cheever-thayer_wired-love#5]
There about a dozen spots where a semicolon is used instead of a comma at the end of a bit of dialog. In most cases, I can't see any reason for this. Would you accept a pull request to standardize some of these to commas?

> “Yes;” Nattie answered, briefly.

> “Yes;” said Cyn, seriously, “and thank Heaven that it was love, and not disappointment, that came!”

> “I am so sorry;” she said, sadly, “so very, very sorry![…]”

> “I think not;” Cyn answered.

There are a couple places where they do serve a purpose, and which I would leave as-is. For example:

> He capped the climax, however, by accidentally dropping a large handful, warm, on top of Celeste’s head, aggravating the offense by telling her to “go quick and soak her head;” which, although it was what she eventually did, was too much like a certain slang phrase much in vogue, for human nature to endure; and giving him an angry look, the only one on record ever given by her to a man, she rushed from the room, and was seen no more that evening.

**Comment by acabal** [comment]
Yes, you can do that in an editorial commit. Thanks!
